// Mocks generated by Mockito 5.4.5 from annotations
// in f1_mobile_frontend_demo/test/core/repositories/f1_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:f1_mobile_frontend_demo/core/services/f1_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [F1Service].
///
/// See the documentation for Mockito's code generation for more information.
class MockF1Service extends _i1.Mock implements _i3.F1Service {
  MockF1Service() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> getF1Resource({
    required _i3.F1Resource? resource,
    int? pageLimit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getF1Resource,
          [],
          {
            #resource: resource,
            #pageLimit: pageLimit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getF1Resource,
            [],
            {
              #resource: resource,
              #pageLimit: pageLimit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}
