name: f1_mobile_frontend_demo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0                                                             # MIT
  flutter_bloc: ^9.0.0                                                    # MIT
  freezed: ^2.5.8                                                         # MIT
  equatable: ^2.0.7                                                       # MIT
  json_serializable: ^6.9.3                                               # BSD-3-Clause
  json_annotation: ^4.9.0                                                 # BSD-3-Clause
  flutter_screenutil: ^5.9.3                                              # Apache-2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
